# Generated by Django 3.2.5 on 2021-07-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=30, unique=True)),
                ('insta_id', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('follower', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'influencer',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=30)),
                ('post_id', models.CharField(max_length=30, unique=True)),
                ('comments_count', models.PositiveIntegerField()),
                ('likes_count', models.PositiveIntegerField()),
                ('post_date', models.DateField()),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
